### ISSUE TITLE
TestTrie_IDLeakageDense test failing consistently

### ISSUE THREAD

**Issue by yujuhong** [tchap/go-patricia#24]
I was using docker v1.11 (which calls `NewTrie` on container creation) and observe a slow memory increase. I then ran a small test to create and immediately delete a container for thousands of times. The heap profile shows that `github.com/tchap/go-patricia/patricia.NewTrie` accumulates more memory over time even though the number of containers remains the same. I instrumented docker to make sure that the key is deleted from the Trie on container deletion, so the trie should remain a constant size over time. 

I modified the `TestTrie_IDLeakageDense` test to use a UUID as a key (to be more consistent with how docker is using it), and change the test to perform insertion followed by deletion for 10 million times. 

```go
func genTestData() *testData {
        // generate a random hash as a key
        key, _ := uuid.NewUUID()
        return &testData{key: key.String(), value: "o", retVal: success}
}
```
```go
        for i := 0; i < 10000000; i++ {
                if ok := trie.Insert(Prefix(v.key), v.value); ok != v.retVal {
                        t.Errorf("Unexpected return value, expected=%v, got=%v", v.retVal, ok)
                }

                if ok := trie.Delete([]byte(v.key)); ok != v.retVal {
                        t.Errorf("Unexpected return value, expected=%v, got=%v", v.retVal, ok)
                }
        }
```

The test consistently fails with increased heap usage, e.g., 
```console
$ go test
--- FAIL: TestTrie_IDLeakageDense (11.70s)
	patricia_dense_test.go:60: Size=0, Total=1, Trie state:
		 <nil>
		
	patricia_dense_test.go:61: Heap space leak, grew 79424 bytes (310016 to 389440)
FAIL
exit status 1
FAIL	github.com/tchap/go-patricia/patricia	11.735s
```

I noticed that the test has a [constant overhead](https://github.com/tchap/go-patricia/blob/2afe4fa257af06a5379ca7412d6b383876187cb6/patricia/patricia_dense_test.go#L17) set to 25000 byte (introduced in #20).  Why is that and is an increase in memory usuage expected for the test?

**Comment by tchap** [comment]
Looks like I will have to investigate this issue more when I have time.

**Comment by yujuhong** [comment]
@tchap any news on the investigation?

**Comment by tchap** [comment]
@yujuhong I am kinda busy at the moment, but I will try to do something about this during the weekend or Monday/Tuesday.

**Comment by tchap** [comment]
@yujuhong There is definitely a leak. I just run the test myself and the trie is full of nodes with weird prefixes and values set to `nil`. So I am going to take a look why that is so...

**Comment by tchap** [comment]
```
$ go test -v -run TestTrie_IDLeakageDense
=== RUN   TestTrie_IDLeakageDense
--- FAIL: TestTrie_IDLeakageDense (0.04s)
	patricia_dense_test.go:259: Size=0, Total=17, Trie state:
		 <nil>
		  3 <nil>
		    24446eb-a <nil>
		      2bd-42cb-b <nil>
		        749-ab2abb <nil>
		    aa6f2df-ef <nil>
		      db-4420-9e <nil>
		        28-14e987d <nil>
		  634cf3ee-9 <nil>
		    bc6-44db-b <nil>
		      4c9-b7c759 <nil>
		  9d3ea059-2 <nil>
		    82c-4246-8 <nil>
		      956-b9382e <nil>
		  c24a8972-7 <nil>
		    788-49ee-8 <nil>
		      125-a8d652 <nil>
		
	patricia_dense_test.go:260: Heap space leak, grew 4112 bytes (115272 to 119384)
FAIL
exit status 1
FAIL	github.com/tchap/go-patricia/patricia	0.058s
```

**Comment by tchap** [comment]
On the other hand, in case the trie dump is really just `<nil>`, it is indeed GC overhead... So the output you posted at the beginning, @yujuhong , was not really a bug. But what I posted right above is definitely a bug.

**Comment by tchap** [comment]
@yujuhong See https://github.com/tchap/go-patricia/commit/e02f830046f1aa8e08390304399fe483434eb8ad

**Comment by yujuhong** [comment]
Thanks for looking into this!

> On the other hand, in case the trie dump is really just <nil>, it is indeed GC overhead... So the output you posted at the beginning, @yujuhong , was not really a bug. But what I posted right above is definitely a bug.

I my test, I called GC couple of times and waited for a long time (i.e., tens of minutes), but the memory never got reclaimed. Not sure why that's the case. I'm glad that you discovered a real leak though :)

**Comment by tchap** [comment]
@yujuhong You want to test the commit or shall I just merge it and we see whether it helps?

**Comment by yujuhong** [comment]
I won't have the time to test it today, but I'll try doing that in a couple of days. Thanks a lot!

**Comment by yujuhong** [comment]
I patched docker 1.11.1 with your fix, and see the difference in RSS memory.
Without the fix, docker daemon's RSS memory increased ~6700 bytes after creating and deleting 2000 containers.
With the fix, the memory increased ~800 bytes only.

The fix seems to have worked quite well.

**Comment by tchap** [comment]
@yujuhong I will merge the commit then...

**Comment by yujuhong** [comment]
@tchap thanks!

**Comment by darkprisco** [comment]
Sorry guys but I didn't get the point!
My problem is that I have several pods running on K8S cluster and over there I can see that all pods are using something like 4 GB of RAM and there is "dockerd" daemon is using 7 GB of RAM.
Is this normal?
