### ISSUE TITLE
Testsuite fails with gccgo 6.1

### ISSUE THREAD

**Issue by michael-holzheu** [tchap/go-patricia#26]
The s390x (Mainframe) Docker CI runs with gccgo 6.1. Currently it fails because Docker updated its go-patricia from v2.1.0 to v2.2.4 (see issue docker/docker#25360).

While investigating the problem I found out that the go-patricia testsuite does not run for version 2.2.4 with gccgo 6.1 also on amd64:

1) Start gcc:6.1 image and get go-patricia code:
```
$ docker run -ti --rm gcc:6.1 bash
root@a0f013b0c10a:~# mkdir -p /root/go/src
root@a0f013b0c10a:~# cd /root/go/src
root@a0f013b0c10a:~/go/src# export GOPATH=/root/go
root@a0f013b0c10a:~/go/src# go get github.com/satori/go.uuid
root@a0f013b0c10a:~/go/src# git clone https://github.com/tchap/go-patricia.git github.com/tchap/go-patricia
```

2) Try with version 2.1.0 (works):
```
root@a0f013b0c10a:~/go/src# cd github.com/tchap/go-patricia/patricia && git checkout v2.1.0 && cd -
HEAD is now at d87fea6... Merge pull request #14 from ishidawataru/fix_walk
root@a0f013b0c10a:~/go/src# go test github.com/tchap/go-patricia/patricia
ok      github.com/tchap/go-patricia/patricia   4.646s
```

3) Try with version 2.2.4 (fails):
```
root@a0f013b0c10a:~/go/src# cd github.com/tchap/go-patricia/patricia && git checkout v2.2.4 && cd -
HEAD is now at 0d76659... Fix Delete memory leak and other bugs found
root@a0f013b0c10a:~# go test github.com/tchap/go-patricia/patricia

--- FAIL: TestTrie_DeleteLeakageDense (0.00s)
panic: runtime error: index out of range [recovered]
        panic: runtime error: index out of range


        :0

        :0

github_com_tchap_go_patricia_patricia.remove.pN53_github_com_tchap_go_patricia_patricia.sparseChildList
        /root/go/src/github.com/tchap/go-patricia/patricia/children.go:73
github_com_tchap_go_patricia_patricia.Delete.pN42_github_com_tchap_go_patricia_patricia.Trie
        /root/go/src/github.com/tchap/go-patricia/patricia/patricia.go:302
github_com_tchap_go_patricia_patricia.TestTrie_DeleteLeakageDense
        /root/go/src/github.com/tchap/go-patricia/patricia/patricia_dense_test.go:196

        :0

goroutine 16 [chan receive]:

        :0


created by main
        /usr/src/gcc/libgo/runtime/go-main.c:54

        :0

        :0

goroutine 17 [syscall]:
        goroutine in C code; stack unavailable

goroutine 18 [finalizer wait]:

goroutine 19 [GC sweep wait]:
        :0

        :0
FAIL    github.com/tchap/go-patricia/patricia   0.044s
```

The testsuite runs well with golang 1.7rc5.

I am not sure if this is a gccgo or patricia problem. Could you verify that there is no "index out of range" problem in [children.go:73](https://github.com/tchap/go-patricia/blob/0d76659452e3b71b109c45196b32e662db2ad16a/patricia/children.go#L73)?

**Comment by michael-holzheu** [comment]
ping @tchap

**Comment by michael-holzheu** [comment]
Commit e30d10f29301fa31d4520d7a6d0b7bac132134e5 introduced the problem:

```
commit e30d10f29301fa31d4520d7a6d0b7bac132134e5
Author: Andrew Stone <a@stoney.io>
Date:   Thu Oct 1 12:07:13 2015 -0400

    Fix memory leak in sparse list child removal

diff --git a/patricia/children.go b/patricia/children.go
index 26c5613..47ebf15 100644
--- a/patricia/children.go
+++ b/patricia/children.go
@@ -79,7 +79,9 @@ func (list *sparseChildList) replace(b byte, child *Trie) {
 func (list *sparseChildList) remove(child *Trie) {
        for i, node := range list.children {
                if node.prefix[0] == child.prefix[0] {
-                       list.children = append(list.children[:i], list.children[i+1:]...)
+                       list.children, list.children[len(list.children)-1] =
+                               append(list.children[:i], list.children[i+1:]...),
+                               nil
                        return
                }
        }
```

**Comment by michael-holzheu** [comment]
We can reproduce the problem with the following simple test program:
```
package main
import "fmt"

func main() {
        test_array := [...]byte{0x0, 0x1, 0x2}
        test_splice := test_array[:]
        test_splice, test_splice[2] = append(test_splice[:1], test_splice[2:]...), 0x0
        fmt.Printf("Are spices implemented correctly?\n")
}
```

**Comment by michael-holzheu** [comment]
Interestingly the previous example works with golang (and fails with gccgo), but the following fails (as expected) also with golang:

```
package main
import "fmt"

func main() {
        test_array := [...]byte{0x0, 0x1, 0x2}
        test_splice := test_array[:]
        test_splice = append(test_splice[:1], test_splice[2:]...)
        test_splice[2] = 0x0
        fmt.Printf("Are splices implemented correctly?\n")
}
```
```
$ ./splice 
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x10f240, 0xc82000a0b0)
        /usr/local/go/src/runtime/panic.go:464 +0x400
main.main()
        /home/holzheu/splice.go:8 +0x192
```

**Comment by michael-holzheu** [comment]
```
list.children, list.children[len(list.children)-1] =
                     append(list.children[:i], list.children[i+1:]...),
                     nil
```
So what about the following theory:

Let's assume "list.children" has 3 elements and we want do delete the one in the middle (i=1). After append it only has 2 elements.

#### golang
1) `len(list.children)-1` = 2
2) `list.children[2] = nil` -> *works* because we still have 3 elements
3) `list.children = append(list.children[:1], list.children[2:]...)` -> 2 elements

#### gccgo:
1) `len(list.children)-1` = 2
2) `list.children = append(list.children[:1], list.children[2:]...)` -> 2 elements
3) `list.children[2] = nil` -> *fails* because we have only 2 elements

What does the go standard say about the ordering here?

**Comment by michael-holzheu** [comment]
> What does the go standard say about the ordering here?

@mundaym could you advise?

**Comment by michael-holzheu** [comment]
Thinking a bit more: If golang first sets list.children[2] to nil and then does the append, we wouldn't we loose the last element? Confusing...

**Comment by mundaym** [comment]
It's an interesting case. The [spec ](https://golang.org/ref/spec#Order_of_evaluation) says this:

> At package level, initialization dependencies determine the evaluation order of individual initialization expressions in variable declarations. Otherwise, when evaluating the operands of an expression, assignment, or return statement, all function calls, method calls, and communication operations are evaluated in lexical left-to-right order.
>
>  For example, in the (function-local) assignment
>
> `y[f()], ok = g(h(), i()+x[j()], <-c), k()`
>
>the function calls and communication happen in the order `f()`, `h()`, `i()`, `j()`, `<-c`, `g()`, and `k()`. **However, the order of those events compared to the evaluation and indexing of x and the evaluation of y is not specified**. 

My interpretation of the spec is that the index evaluation on the left hand side may happen before or after the append. I think therefore that both compilers follow the spec correctly.

I wouldn't be surprised if gc evaluated the indexes on the left first (i.e. takes the address of the indexed element to be assigned to and does the bounds check), but then assigned nil last, which would appear to be the behavior we see.

I also found this golang-nuts post which seems to reach the same conclusion: https://groups.google.com/d/topic/golang-nuts/6hfV8icSGGQ/discussion

**Comment by tchap** [comment]
Will take a look when I have some spare time. Thanks.

**Comment by tchap** [comment]
In any case, I will gladly accept any PR just putting some sugar around to void the issue ;-)

**Comment by tchap** [comment]
@michael-holzheu Check https://github.com/tchap/go-patricia/commit/66b519a57063db2f7d2b08bc5b449023f9e1eaf2

**Comment by michael-holzheu** [comment]
> @michael-holzheu Check 66b519a

With gccgo:
```
root@22f708fa7608:~/go/src/github.com/tchap/go-patricia/patricia# go test github.com/tchap/go-patricia/patricia
--- FAIL: TestTrie_DeleteLeakageDense (3.44s)
        patricia_dense_test.go:203: Size=0, Total=1, Trie state:
                 <nil>

        patricia_dense_test.go:204: Heap space leak, grew 4752 bytes (215480 to 220232)
FAIL
FAIL    github.com/tchap/go-patricia/patricia   8.825s
```

If I add the following, it works:

```go
diff --git a/patricia/children.go b/patricia/children.go
index 0d2fa29..80bef79 100644
--- a/patricia/children.go
+++ b/patricia/children.go
@@ -70,6 +70,7 @@ func (list *sparseChildList) add(child *Trie) childList {
 func (list *sparseChildList) remove(b byte) {
        for i, node := range list.children {
                if node.prefix[0] == b {
+                       list.children[i] = nil
                        list.children = append(list.children[:i], list.children[i+1:]...)
                        return
                }
```

... which is (again) a bit confusing to me. My naive assumption was that we delete element "i" and reference will go away, too.

@mundaym : You can probably explain also this go mystery ;-)

**Comment by michael-holzheu** [comment]
> @mundaym : You can probably explain also this go mystery ;-)

After a bit more thinking I perhaps have understood now: Let's say we have a go array "a" of three elements 1, 2, 3 and a splice "s" that covers all elements:

```
   +---+---+---+
a: | 1 | 2 | 3 |
   +---+---+---+
     ^   ^   ^
     |   |   |
   +---+---+---+
s: | 1 | 2 | 3 |
   +---+---+---+
```


After `s = append(s[:1],s[2:] it looks like the following:

```
   +---+---+---+
a: | 1 | 2 | 3 |
   +---+---+---+
     ^       ^  
     |       |
     |   +---+
     |   |  
   +---+---+
s: | 1 | 3 | 
   +---+---+
```
So element 2 is still there. If it is a reference to an object, the object will not be deleted. On the other hand: The object can't be accessed any more if there is no other splice around. So the compiler could release the object, no?

**Comment by tchap** [comment]
@michael-holzheu I added the nil assigment and also added another approach that should work:

7b003c9 Another approach to #26
26834ea Fix remove() in the sparse children mode

Not really sure which one is better...

**Comment by michael-holzheu** [comment]
> @michael-holzheu I added the nil assigment and also added another approach that should work:

In the meantime I noticed that __also with the nil assignment__ we get the __heap error__ from time to time. @mundaym thinks that reducing the splice size is sufficient for the the go runtime to automatically drop the references. So I assume it is just a garbage collection timing issue. 

> Not really sure which one is better...

I personally would prefer your "copy" solution 7b003c925a6ee7689fd645a4dafd94fc990ea24f since we found this as the proposed method for deleting elements in "The Go Programming Language" from Alan A. A. Donovan and Brian W. Kernighan.

It would be also great if you could create a new release that we then can include in Docker.

**Comment by tchap** [comment]
@michael-holzheu Merged and tagged as `v2.2.5`

**Comment by michael-holzheu** [comment]
> @michael-holzheu Merged and tagged as v2.2.5

@tchap : Version v2.2.5 has been included in Docker with PR docker/docker#25510

Thanks!

**Comment by tchap** [comment]
@michael-holzheu You might be interested in `v2.2.6` since it improves the logic and fixes potential memory leak in `remove()`. See 666120d.

**Comment by michael-holzheu** [comment]
> @michael-holzheu You might be interested in v2.2.6 since it improves the logic and fixes potential memory leak in remove(). See 666120d.

@tchap Are you really sure that this is required? I thought that the go runtime will do the garbage collection correctly also with the previous version.

**Comment by tchap** [comment]
@michael-holzheu Well, according to https://github.com/golang/go/wiki/SliceTricks there is a potential leak. Tests are not triggering any warning, though, so I am not sure. It could be fine even in the version you are using...

**Comment by michael-holzheu** [comment]
> Well, according to https://github.com/golang/go/wiki/SliceTricks there is a potential leak. 

As @ddingel mentioned in https://github.com/tchap/go-patricia/commit/666120de432aea38ab06bd5c818f04f4129882c9#commitcomment-18674856,  this is probably  "dependent on the go implementation".

Anyway... I suggested `v2.2.6` in https://github.com/docker/docker/issues/25360#issuecomment-240455666.

**Comment by tchap** [comment]
@michael-holzheu I don't really understand what can be dependent on the implementation in that case. The item being removed is replaced with the last element, the last element is reset to `nil` and then the whole slice is shortened by 1...

**Comment by michael-holzheu** [comment]
> @michael-holzheu I don't really understand what can be dependent on the implementation in that case. The item being removed is replaced with the last element, the last element is reset to nil and then the whole slice is shortened by 1...

Wilt `v2.2.4`no doubt, but I meant your implementation in `v2.2.5`.

**Comment by tchap** [comment]
@michael-holzheu Yeah, ok. But 2.2.6 should be cool.

**Comment by ddingel** [comment]
Sadly this does not fix the bug in all variants. With @michael-holzheu I tried to understand the current go memory management and from that it does look like there is a missing FreeOSMemory() call after letting runtime.GC() run.
```
func heapAllocatedBytes() uint64 {
	runtime.GC()

	ms := runtime.MemStats{}
	runtime.ReadMemStats(&ms)
	return ms.Alloc
}
```
[https://github.com/tchap/go-patricia/blob/master/patricia/patricia_dense_test.go#L212-L218](url)

That is also the way it is done within the golang tests.

**Comment by tchap** [comment]
So, let's sum it up since I am getting a bit lost in who is commenting on `2.2.5` and who on `2.2.6`, but I think that `2.2.6` is fine.

Not sure whether we need to call `FreeOSMemory`. Would have to check what stats are actually returned. If it is about what is allocated by the app, it does not matter really whether it was returned to Go runtime or the OS, right? We only need to know that it is not allocated. So I would need to check what is hidden behind this `Alloc` field :-)

**Comment by michael-holzheu** [comment]
> So, let's sum it up since I am getting a bit lost in who is commenting on 2.2.5 and who on 2.2.6, but I think that 2.2.6 is fine.

Yes IMHO regarding this issue your release `2.2.6` is good. Sorry for confusing you.

> Not sure whether we need to call FreeOSMemory

At least we noticed that the following testcase fails from time to time with gccgo:
```bash
# go test github.com/tchap/go-patricia/patricia
--- FAIL: TestTrie_DeleteLeakageDense (3.49s)
        patricia_dense_test.go:204: Size=0, Total=1, Trie state:
                 <nil>

        patricia_dense_test.go:205: Heap space leak, grew 6192 bytes (215320 to 221512)
FAIL
FAIL    github.com/tchap/go-patricia/patricia   9.391s
```

After applying the following patch ...

```go
diff --git a/patricia/patricia_dense_test.go b/patricia/patricia_dense_test.go
index b50881e..e7dd84b 100644
--- a/patricia/patricia_dense_test.go
+++ b/patricia/patricia_dense_test.go
@@ -8,6 +8,7 @@ package patricia
 import (
        "runtime"
        "testing"
+       "runtime/debug"
 
        "github.com/satori/go.uuid"
 )
@@ -211,6 +212,7 @@ func TestTrie_DeleteLeakageDense(t *testing.T) {
 
 func heapAllocatedBytes() uint64 {
        runtime.GC()
+       debug.FreeOSMemory()
 
        ms := runtime.MemStats{}
        runtime.ReadMemStats(&ms)
```

... the tests seem to pass reliably:

```bash
# go test github.com/tchap/go-patricia/patricia
ok      github.com/tchap/go-patricia/patricia   9.476s
```
